### ISSUE TITLE
bs4DashControlbar controlbar_overlay = FALSE only works with 250px width

### ISSUE THREAD

**Issue by analytichealth** [RinteRface/bs4Dash#128]
Hi David,
With any value greater than the default width = 250, the controlbar overlays the body content, even when controlbar_overlay = FALSE.
Please see example below.

Thank you 

```
library(shiny)
library(bs4Dash)

shiny::shinyApp(
  ui = bs4DashPage(
   title = "Basic Dashboard",
   navbar = bs4DashNavbar(),
   sidebar = bs4DashSidebar(),
   controlbar_collapsed = FALSE,
   controlbar_overlay = FALSE,
   controlbar = bs4DashControlbar(
        inputId = 'controlbar_id', 
        width = 450,
        pinned = FALSE,
        h4('hello world')
      ),
   body = bs4DashBody(
   	bs4Card(inputId = 'test_id', width = 12)
   )
  ),
  server = function(input, output) {}
)
```

**Comment by DivadNojnarg** [comment]
You'll also notice the controlbar does not properly push the body content (only from 250px) and overlays from 200px. There is more work to do actually. I was actually missing couple more rules:

```css
.control-sidebar-slide-open.control-sidebar-push .content-wrapper, 
              .control-sidebar-slide-open.control-sidebar-push .main-footer, 
              .control-sidebar-slide-open.control-sidebar-push-slide .content-wrapper, 
              .control-sidebar-slide-open.control-sidebar-push-slide .main-footer {
                margin-right: $controlbar-width;
              }

              @media (min-width: 768px)
                body:not(.sidebar-mini-md) .content-wrapper, 
                body:not(.sidebar-mini-md) .main-footer, 
                body:not(.sidebar-mini-md) .main-header {
                  transition: margin-left .3s ease-in-out;
                  margin-left: $controlbar-width;
                }
```
