### ISSUE TITLE
Multiple bs4SidebarHeader paddings

### ISSUE THREAD

**Issue by James-G-Hill** [RinteRface/bs4Dash#135]
When there is more than one bs4SidebarHeader the text in the first header is aligned further left than all subsequent headers.  The subsequent headers define the alignment differently with `.nav-sidebar .nav-header:not(:first-of-type)`.

**Comment by DivadNojnarg** [comment]
This rules has been defined by the AdminLTE3 authors. The reason appears when using `sidebarUserPanel`. If you use for all items:

```css
.nav-sidebar .nav-header {
    padding: 1.7rem 1rem .5rem;
}
```

there is too much vertical space between the user panel and the title. However I agree all title should be aligned. I therefore added the custom rule:

```css
.nav-sidebar .nav-header {
    padding: 0rem 1rem .5rem;
}
```

which avoids the unnecessary vertical space, while aligning all titles.
