### ISSUE TITLE
bsModal Size

### ISSUE THREAD

**Issue by lemuelemos** [RinteRface/bs4Dash#173]
How can i set the modal size from bsModal package? I used to put tags $ head ($ style tags (". Modal-dialog {width: 2000px;}")) in code, and it worked. How can i do it in bs4dash?

**Comment by DivadNojnarg** [comment]
`{shinyBS}` relies on Bootstrap 3, while `{bs4Dash}` relies on Bootstrap 4. Therefore, I would avoid for compatibility reasons. 
There is also another issue when setting a fix width: your modal may not render well on some devices (mobiles). Below is the CSS controlling some modal properties, specifically the size. You see that depending on the screen size, the `modal-xl` does not have the same width, which makes sense:

```css
@media (min-width: 576px) {
  .modal-dialog {
    max-width: 500px;
    margin: 1.75rem auto;
  }
  .modal-dialog-scrollable {
    max-height: calc(100% - 3.5rem);
  }
  .modal-dialog-scrollable .modal-content {
    max-height: calc(100vh - 3.5rem);
  }
  .modal-dialog-centered {
    min-height: calc(100% - 3.5rem);
  }
  .modal-dialog-centered::before {
    height: calc(100vh - 3.5rem);
    height: -webkit-min-content;
    height: -moz-min-content;
    height: min-content;
  }
  .modal-content {
    box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.5);
  }
  .modal-sm {
    max-width: 300px;
  }
}

@media (min-width: 992px) {
  .modal-lg,
  .modal-xl {
    max-width: 800px;
  }
}

@media (min-width: 1200px) {
  .modal-xl {
    max-width: 1140px;
  }
}
```

For instance, the last rules says: "if the screen size is at least 1200px, the modal width is 1140 px, that is 95% of the total width". 

What you could do is create a custom class and set the `width` depending on the screen size you want to consider:

```css
/* Larger rule */
@media (min-width: 2100px) {
  .modal-custom {
    max-width: 2000px;
  }
}
```

For now, you can use `shiny::modalDialog` that has the same class as Bootstrap 4:

```r
library(shiny)
library(bs4Dash)

modal <- modalDialog(
  title = "Somewhat important message",
  "This is a somewhat important message.",
  easyClose = TRUE,
  footer = NULL
)

modal$children[[1]]$attribs$class <- "modal-custom"

shinyApp(
  ui = dashboardPage(
    header = dashboardHeader(
      title = dashboardBrand(
        title = "My dashboard",
        color = "primary",
        href = "https://adminlte.io/themes/v3",
        image = "https://adminlte.io/themes/v3/dist/img/AdminLTELogo.png"
      )
    ),
    sidebar = dashboardSidebar(),
    body = dashboardBody(
      tags$head(
        tags$style(
          "@media (min-width: 2100px) {
            .modal-custom {
              max-width: 2000px;
            }
          }
          "
        )
      )
    ),
    controlbar = dashboardControlbar(),
    title = "DashboardPage"
  ),
  server = function(input, output) { 
    observe({
      showModal(modal)
    })
  }
)
```
